### ISSUE TITLE
Savant crashes on Unicorn sacrifice

### ISSUE THREAD

**Issue by jensvieweger** [datalurkur/Kittens#25]
As soon the savant wants to sacrifice Unicorns, it crashes:

Error code:
`An error occured in the Kitten Savant plugin!
Contact the developer.
Details:
Error encountered during tick
TypeError: button.controller.sacrifice is not a function
at Object.sacrificeUpTo (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:356:36)
at tree.traverse (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:462:30)
at Object.traverse (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/costData.js:276:25)
at Object.traverse (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/costData.js:503:64)
at Object.traverse (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/costData.js:273:95)
at analysisData.priorityOrder.forEach (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:441:22)
at Array.forEach (<anonymous>)
at Object.pursuePriority (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:435:45)
at Object.standardTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:832:36)
at Object.unsafeTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:886:22)
`

Happens using

-  Kittens Savant Extension 0.2.2
- Vivaldi 1.15.1147.64
- KittensGame 1.4.7.0.a-y

Looks like something was renamed and can't be found by the savant?

**Comment by datalurkur** [comment]
Fixed in version 0.2.3
