### ISSUE TITLE
tem.controller.upgradeCallback is not a function

### ISSUE THREAD

**Issue by McGreggin** [datalurkur/Kittens#26]
An error occured in the Kitten Savant plugin!
Contact the developer.
Details:
Error encountered during tick
TypeError: item.controller.upgradeCallback is not a function
at Object.upgradeItems (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:680:37)
at Object.standardTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:854:18)
at Object.unsafeTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:886:22)
at Object.tick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:896:22)
at chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:934:83

**Comment by McGreggin** [comment]
Additionally, while I can see you've corrected the issue with the unicorn in v .23 the extension still showing is v .22 here: https://chrome.google.com/webstore/detail/kitten-savant/ofaeajfjlokfnlbnhclggbjmfhgjbepf

**Comment by datalurkur** [comment]
Latest plugin (v .24) should have the fix.
