### ISSUE TITLE
New issue with latest version

### ISSUE THREAD

**Issue by McGreggin** [datalurkur/Kittens#28]
An error occured in the Kitten Savant plugin!
Contact the developer.
Details:
Error encountered during tick
TypeError: village.sendHuntersImpl is not a function
at Object.huntHack (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/base.js:202:38)
at Object.hunt (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/base.js:177:29)
at Object.convertCatpower (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:594:26)
at Object.standardTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:863:18)
at Object.unsafeTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:910:22)
at Object.tick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:926:22)
at chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:964:83

**Comment by datalurkur** [comment]
Fixed in 0.2.5

**Comment by McGreggin** [comment]
@datalurkur when will this be added/updated on apps?

**Comment by datalurkur** [comment]
When google approves the new version of the plugin.
