### ISSUE TITLE
TypeError: item.controller.upgradeCallback is not a function

### ISSUE THREAD

**Issue by McGreggin** [datalurkur/Kittens#29]
An error occured in the Kitten Savant plugin!
Contact the developer.
Details:
Error encountered during tick
TypeError: item.controller.upgradeCallback is not a function
at Object.upgradeItems (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:704:37)
at Object.standardTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:878:18)
at Object.unsafeTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:910:22)
at Object.tick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:926:22)
at chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:964:83

v 25

**Comment by datalurkur** [comment]
Fixed in 0.2.6
