### ISSUE TITLE
TypeError: religion.getTranscendenceLevel is not a function

### ISSUE THREAD

**Issue by McGreggin** [datalurkur/Kittens#30]
An error occured in the Kitten Savant plugin!
Contact the developer.
Details:
Error encountered during tick
TypeError: religion.getTranscendenceLevel is not a function
at Object.transcendHack (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/base.js:263:36)
at Object.transcend (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/base.js:249:25)
at chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:491:50
at Object.traverse (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/costData.js:277:25)
at chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:441:22
at Array.forEach (<anonymous>)
at Object.pursuePriority (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:435:45)
at Object.standardTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:869:36)
at Object.unsafeTick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:923:22)
at Object.tick (chrome-extension://ofaeajfjlokfnlbnhclggbjmfhgjbepf/core.js:938:22)

**Comment by datalurkur** [comment]
Fixed in 0.2.7
